//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_REPORT_v7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HourOvertimeTable
    {
        public System.Guid OvertimeID { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.TimeSpan Duration { get; set; }
        public string Shop { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Cooperation { get; set; }
        public System.Guid ReportID { get; set; }
    
        public virtual ReportTable ReportTable { get; set; }
    }
}
