//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_REPORT_v7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT_IMAGES
    {
        public System.Guid ImageID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.Guid> ReportID { get; set; }
    
        public virtual MainTaskTable MainTaskTable { get; set; }
    }
}
