//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_REPORT_v7.Models
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ReIssueTable
    {
        public System.Guid ReIssueID { get; set; }
        [Required]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public System.TimeSpan Time { get; set; }
        [Required]
        [DisplayName("Who")]
        [MaxLength(50, ErrorMessage = "Maximum length can't be more than 50 characters.")]
        public string User { get; set; }
        [Required]
        [DisplayName("What")]
        [MaxLength( 50, ErrorMessage = "Maximum length can't be more than 50 characters." )]
        public string Objective { get; set; }
        [Required]
        [DisplayName("Body Num.")]
        [MaxLength( 50, ErrorMessage = "Maximum length can't be more than 50 characters." )]
        public string BodyNum { get; set; }
        public System.Guid ReportID { get; set; }
    
        public virtual ReportTable ReportTable { get; set; }
    }
}
