//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_REPORT_v7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportTable()
        {
            this.HourOvertimeTable = new HashSet<HourOvertimeTable>();
            this.MainTaskTable = new HashSet<MainTaskTable>();
            this.PasswordTable = new HashSet<PasswordTable>();
            this.PreCheckTable = new HashSet<PreCheckTable>();
            this.PrintersTable = new HashSet<PrintersTable>();
            this.ReIssueTable = new HashSet<ReIssueTable>();
        }
    
        public System.Guid ReportID { get; set; }
        public System.DateTime Date { get; set; }
        public string Shift { get; set; }
        public Nullable<int> Member_One_ID { get; set; }
        public Nullable<int> Member_Two_ID { get; set; }
        public Nullable<int> ShiftID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HourOvertimeTable> HourOvertimeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainTaskTable> MainTaskTable { get; set; }
        public virtual MembersTable MembersTable { get; set; }
        public virtual MembersTable MembersTable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasswordTable> PasswordTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreCheckTable> PreCheckTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintersTable> PrintersTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReIssueTable> ReIssueTable { get; set; }
        public virtual ShiftTable ShiftTable { get; set; }
    }
}
